-- Sprint 10: SLA Rules, Alert Channels, and Alerts
-- ─────────────────────────────────────────────────

-- SLA rules define threshold conditions that the Alert Engine evaluates periodically.
CREATE TABLE sla_rules (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    service_id          UUID         NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(1000),

    -- Signal source: METRICS (PromQL) or LOGS (Elasticsearch aggregation)
    signal_type         VARCHAR(20)  NOT NULL CHECK (signal_type IN ('METRICS', 'LOGS')),

    -- For METRICS rules: the PromQL metric name or expression fragment
    metric_name         VARCHAR(500),

    -- For LOGS rules: the severity level or keyword to count
    log_condition       VARCHAR(500),

    -- Comparison operator and threshold
    operator            VARCHAR(10)  NOT NULL CHECK (operator IN ('GT', 'GTE', 'LT', 'LTE', 'EQ', 'NEQ')),
    threshold           DOUBLE PRECISION NOT NULL,

    -- How far back to look when evaluating (e.g. '5m', '15m', '1h')
    evaluation_window   VARCHAR(20)  NOT NULL DEFAULT '5m',

    -- How many consecutive evaluation cycles must breach before PENDING → FIRING
    pending_periods     INT          NOT NULL DEFAULT 1,

    severity            VARCHAR(20)  NOT NULL DEFAULT 'WARNING' CHECK (severity IN ('CRITICAL', 'WARNING', 'INFO')),
    enabled             BOOLEAN      NOT NULL DEFAULT TRUE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_sla_rules_service_id ON sla_rules(service_id);
CREATE INDEX idx_sla_rules_enabled    ON sla_rules(enabled);

-- Notification channels that can receive alerts.
CREATE TABLE alert_channels (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(255) NOT NULL,

    -- EMAIL, SMS, or MS_TEAMS
    channel_type    VARCHAR(20)  NOT NULL CHECK (channel_type IN ('EMAIL', 'SMS', 'MS_TEAMS')),

    -- JSON blob with channel-specific config:
    --   EMAIL:    { "recipients": ["a@b.com"] }
    --   SMS:      { "phoneNumbers": ["+1234567890"] }
    --   MS_TEAMS: { "webhookUrl": "https://..." }
    config          JSONB        NOT NULL DEFAULT '{}',

    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Junction: which channels are attached to which SLA rule
CREATE TABLE sla_rule_channels (
    sla_rule_id     UUID NOT NULL REFERENCES sla_rules(id)     ON DELETE CASCADE,
    channel_id      UUID NOT NULL REFERENCES alert_channels(id) ON DELETE CASCADE,
    PRIMARY KEY (sla_rule_id, channel_id)
);

-- Alerts generated by the Alert Engine when an SLA rule breaches.
CREATE TABLE alerts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sla_rule_id     UUID         NOT NULL REFERENCES sla_rules(id) ON DELETE CASCADE,
    service_id      UUID         NOT NULL REFERENCES services(id)  ON DELETE CASCADE,

    state           VARCHAR(20)  NOT NULL DEFAULT 'OK' CHECK (state IN ('OK', 'PENDING', 'FIRING', 'RESOLVED')),
    severity        VARCHAR(20)  NOT NULL,

    -- Human-readable message describing the breach
    message         VARCHAR(2000),

    -- Current evaluated value at the time of last evaluation
    evaluated_value DOUBLE PRECISION,

    -- Counter: how many consecutive evaluation cycles the threshold was breached
    pending_count   INT          NOT NULL DEFAULT 0,

    fired_at        TIMESTAMPTZ,
    resolved_at     TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,
    acknowledged_by VARCHAR(255),

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_alerts_sla_rule_id ON alerts(sla_rule_id);
CREATE INDEX idx_alerts_service_id  ON alerts(service_id);
CREATE INDEX idx_alerts_state       ON alerts(state);
